facebook<-read.table('D:/2018 first semester/linear regression/ASSIGNMENT1/facebook.txt',header = TRUE)
GenderX<-factor(facebook$Gender,levels=c(0,1),labels=c('Female','Male'))
facebook[,2]<-GenderX
attach(facebook)
library(car)
library(sm)
par(mfrow=c(1,1))
sm.density.compare(Friends,Gender, xlab='Friends')
colfill<-c(2:(1+length(levels(Gender))))
legend(3.5,1,levels(Gender),fill=colfill)
scatterplot(Friends~Social|Gender,lwd=2,main='Scatter Plot of Friends vs. Social by # Genders',xlab='Social',ylab='Friend',legend.plot=TRUE,id.method='identify')
fit1<-lm(Social[1:6]~Friends[1:6])
fit2<-lm(Social[7:12]~Friends[7:12])
plot(Social[1:6]~Friends[1:6],xlab='Friends',ylab='Social',xlim=c(1.5,3.5),ylim=c(7,15),col='blue')
points(Social[7:12]~Friends[7:12],col='red')
abline(fit1,col='blue')
abline(fit2,col='red')
abline(v=2.5,lty=3,h=y)
abline(v=3,lty=3,h=y)
fit.all<-lm(Friends~Social+Gender+Social:Gender)
summary(fit.all)
fit.1<-update(fit.all,~.-Social:Gender)
summary(fit.1)
fit.2<-update(fit.1,~.-Gender)
summary(fit.2)
library(leaps)
leapsfacebook<-regsubsets(Friends~Social+Gender+Social:Gender,data=facebook,nbest = 3)
plot(leapsfacebook,scale='adjr2')
par(mfrow=c(2,2))
plot(fit.2)
durbinWatsonTest(fit.2)
