```{r}
#load the data
library(GGally)
co2<-read.csv('NZCO2.csv',header = TRUE)
head(co2)
dim(co2)
summary(co2)
ggpairs(co2)
library(ggplot2)
plot1 <- ggplot(co2, aes(x=Year,y=CO2)) + geom_point()
plot1 <- plot1 + theme_bw()
plot1
plot2 <- ggplot(co2, aes(x=Year,y=CO2_per_capita)) + geom_point()
plot2 <- plot2 + theme_bw()
plot2
plot3 <- ggplot(co2, aes(x=Year,y=Population)) + geom_point()
plot3 <- plot3 + theme_bw()
plot3
```

```{r}
library(gam)
yearCO2_per_capita_1<- gam(CO2_per_capita ~ s(Year, spar=0.1), data=co2)
scapital1<-summary(yearCO2_per_capita_1)
scapital1
R1_1 <- (scapital1$null.deviance-scapital1$deviance)/scapital1$null.deviance
R1_1 
co2$fits1 <- fitted(yearCO2_per_capita_1) 
Plot101 <- ggplot(co2, aes(x=Year, y=CO2_per_capita)) + geom_point() 
Plot101 <- Plot101 + geom_line(aes(x=Year, y=fits1), color="red")
Plot101

yearCO2_per_capita_3<- gam(CO2_per_capita ~ s(Year, spar=0.3), data=co2)
scapital3<-summary(yearCO2_per_capita_3)
scapital3
R1_3 <- (scapital3$null.deviance-scapital3$deviance)/scapital3$null.deviance
R1_3 
co2$fits3 <- fitted(yearCO2_per_capita_3)
Plot103 <- ggplot(co2, aes(x=Year, y=CO2_per_capita)) + geom_point() 
Plot103 <- Plot103 + geom_line(aes(x=Year, y=fits3), color="red")
Plot103

yearCO2_per_capita_5<- gam(CO2_per_capita ~ s(Year, spar=0.5), data=co2)
scapital5<-summary(yearCO2_per_capita_5)
scapital5
R1_5 <- (scapital5$null.deviance-scapital5$deviance)/scapital5$null.deviance
R1_5 
co2$fits5 <- fitted(yearCO2_per_capita_5)
Plot105 <- ggplot(co2, aes(x=Year, y=CO2_per_capita)) + geom_point() 
Plot105 <- Plot105 + geom_line(aes(x=Year, y=fits5), color="red")
Plot105

yearCO2_per_capita_7<- gam(CO2_per_capita ~ s(Year, spar=0.7), data=co2)
scapital7<-summary(yearCO2_per_capita_7)
scapital7
R1_7 <- (scapital7$null.deviance-scapital7$deviance)/scapital7$null.deviance
R1_7 
co2$fits7 <- fitted(yearCO2_per_capita_7)
Plot107 <- ggplot(co2, aes(x=Year, y=CO2_per_capita)) + geom_point()
Plot107 <- Plot107 + geom_line(aes(x=Year, y=fits7), color="red")
Plot107

yearCO2_per_capita_4<- gam(CO2_per_capita ~ s(Year, spar=0.4), data=co2)
scapital4<-summary(yearCO2_per_capita_4)
scapital4
R1_4 <- (scapital4$null.deviance-scapital4$deviance)/scapital4$null.deviance
R1_4 
co2$fits4 <- fitted(yearCO2_per_capita_4)
Plot104 <- ggplot(co2, aes(x=Year, y=CO2_per_capita)) + geom_point()
Plot104 <- Plot104 + geom_line(aes(x=Year, y=fits4), color="red")
Plot104
```
```{r}
yearco2_01<- gam(CO2 ~ s(Year, spar=0.1), data=co2)
sco21<-summary(yearco2_01)
sco21
R2_1 <- (sco21$null.deviance-sco21$deviance)/sco21$null.deviance
R2_1 
co2$fits01 <- fitted(yearco2_01) 
Plot201 <- ggplot(co2, aes(x=Year, y=CO2)) + geom_point() 
Plot201 <- Plot201 + geom_line(aes(x=Year, y=fits01), color='red') 
Plot201

yearco2_03<- gam(CO2 ~ s(Year, spar=0.3), data=co2)
sco23<-summary(yearco2_03)
sco23
R2_3 <- (sco23$null.deviance-sco23$deviance)/sco23$null.deviance
R2_3 
co2$fits03 <- fitted(yearco2_03) 
Plot203 <- ggplot(co2, aes(x=Year, y=CO2)) + geom_point() 
Plot203 <- Plot203 + geom_line(aes(x=Year, y=fits03), color='red')
Plot203
  
yearco2_05<- gam(CO2 ~ s(Year, spar=0.5), data=co2)
sco25<-summary(yearco2_05)
sco25
R2_5 <- (sco25$null.deviance-sco25$deviance)/sco25$null.deviance
R2_5 
co2$fits05 <- fitted(yearco2_05)
Plot205 <- ggplot(co2, aes(x=Year, y=CO2)) + geom_point() 
Plot205 <- Plot205 + geom_line(aes(x=Year, y=fits05), color='red')
Plot205

yearco2_07<- gam(CO2 ~ s(Year, spar=0.7), data=co2)
sco27<-summary(yearco2_07)
sco27
R2_7 <- (sco27$null.deviance-sco27$deviance)/sco27$null.deviance
R2_7 
co2$fits07 <- fitted(yearco2_07)
Plot207 <- ggplot(co2, aes(x=Year, y=CO2)) + geom_point() 
Plot207 <- Plot207 + geom_line(aes(x=Year, y=fits07), color='red')
Plot207

```
```{r}
yearpop01<- gam(Population ~ s(Year, spar=0.1), data=co2)
spop1<-summary(yearpop01)
spop1
R3_1 <- (spop1$null.deviance-spop1$deviance)/spop1$null.deviance
R3_1 
co2$fits001 <- fitted(yearpop01) 
Plot301 <- ggplot(co2, aes(x=Year, y=Population)) + geom_point() 
Plot301 <- Plot301 + geom_line(aes(x=Year, y=fits001), color='red') 
Plot301

yearpop03<- gam(Population ~ s(Year, spar=0.3), data=co2)
spop3<-summary(yearpop03)
spop3
R3_3 <- (spop3$null.deviance-spop3$deviance)/spop3$null.deviance
R3_3 
co2$fits003 <- fitted(yearpop03) 
Plot303 <- ggplot(co2, aes(x=Year, y=Population)) + geom_point() 
Plot303 <- Plot303 + geom_line(aes(x=Year, y=fits003), color='red') 
Plot303

yearpop05<- gam(Population ~ s(Year, spar=0.5), data=co2)
spop5<-summary(yearpop05)
spop5
R3_5 <- (spop5$null.deviance-spop5$deviance)/spop5$null.deviance
R3_5 
co2$fits005 <- fitted(yearpop05)
Plot305 <- ggplot(co2, aes(x=Year, y=Population)) + geom_point() 
Plot305 <- Plot305 + geom_line(aes(x=Year, y=fits005), color='red') 
Plot305

yearpop07<- gam(Population ~ s(Year, spar=0.7), data=co2)
spop7<-summary(yearpop07)
spop7
R3_7 <- (spop7$null.deviance-spop7$deviance)/spop7$null.deviance
R3_7
co2$fits007 <- fitted(yearpop07)
Plot307 <- ggplot(co2, aes(x=Year, y=Population)) + geom_point() 
Plot307 <- Plot307 + geom_line(aes(x=Year, y=fits007), color='red') 
Plot307

```
```{r}
lmfit<-lm(Population ~ Year, data=co2)
summary(lmfit)
```


